<a href="https://colab.research.google.com/github/rflsg/Clases/blob/main/Clase29102024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
vec=np.array([2,0,-1,4,5,6,7,8,9,10])
n=len(vec)
print(vec[0:11:3])

[ 2  4  7 10]
12
[ 2  6 10]
[5 6 7 8]


In [34]:
import numpy as np
mat=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ])

print(mat[-1,-1])
print(mat[:,1])
print(mat[1,:])
print(mat[1,1:4])
print(mat[1:3,2])
print(mat[1:3,1:4])

12
[ 2  6 10]
[5 6 7 8]
[6 7 8]
[ 7 11]
[[ 6  7  8]
 [10 11 12]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [44]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])
n=len(a)
q=[]
print(a+b)
for i in range(n):
  s=a[i]*b[i]
  q.append(s)
  l=sum(q)

print(l)

[ 5  7  9 11]
60
